export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const RESET_CART = 'RESET_CART';
export const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE';